# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'browserstack-connection'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  displayName: 'Run Tests'
#  inputs:
#    testSelector: 'testAssemblies'
#    testAssemblyVer2: |
#      **\$(BuildConfiguration)\**\Investigation.dll
#      !**\obj\**
#      !**\*TestAdapter.dll
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**\Investigation.csproj'
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
